[project]
name = "planner"
version = "0.1.0"
description = "Planner app."
readme = "README.md"
authors = [
    { name = "Rajdeep Sandhu", email = "168480080+rajdeep-sandhu@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "marimo[recommended]>=0.24.2",
]

[project.scripts]
planner-app = "planner_app:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.marimo.completion]
signature_hint_on_typing = true

[tool.marimo.package_management]
manager = "uv"

[tool.marimo.display]
default_width = "full"

[tool.marimo.save]
format_on_save = true

[tool.marimo.runtime]
auto_instantiate = true
auto_reload = "autorun"